NoMod               = 0
NoFail              = 2 ** 0
Easy                = 2 ** 1
TouchDevice         = 2 ** 2
Hidden              = 2 ** 3
HardRock            = 2 ** 4
SuddenDeath         = 2 ** 5
DoubleTime          = 2 ** 6
Relax               = 2 ** 7
HalfTime            = 2 ** 8
Nightcore           = 2 ** 9 # Only set along with DoubleTime. i.e: NC only gives 576
Flashlight          = 2 ** 10
Autoplay            = 2 ** 11
SpunOut             = 2 ** 12
Relax2              = 2 ** 13    # Autopilot
Perfect             = 2 ** 14 # Only set along with SuddenDeath. i.e: PF only gives 16416
Key4                = 2 ** 15
Key5                = 2 ** 16
Key6                = 2 ** 17
Key7                = 2 ** 18
Key8                = 2 ** 19
FadeIn              = 2 ** 20
Random              = 2 ** 21
Cinema              = 2 ** 22
Target              = 2 ** 23
Key9                = 2 ** 24
KeyCoop             = 2 ** 25
Key1                = 2 ** 26
Key3                = 2 ** 27
Key2                = 2 ** 28
ScoreV2             = 2 ** 29
Mirror              = 2 ** 30
KeyMod              = Key1 | Key2 | Key3 | Key4 | Key5 | Key6 | Key7 | Key8 | Key9 | KeyCoop
FreeModAllowed      = NoFail | Easy | Hidden | HardRock | SuddenDeath | Flashlight | FadeIn | Relax | Relax2 | SpunOut | KeyMod
ScoreIncreaseMods   = Hidden | HardRock | DoubleTime | Flashlight | FadeIn
